// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto

#include "msg.pb.h"
#include "msg.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace msg {

static const char* NodeService_method_names[] = {
  "/msg.NodeService/SendPrepare",
  "/msg.NodeService/SendNewLogView",
  "/msg.NodeService/SendAccept",
  "/msg.NodeService/SendCommit",
  "/msg.NodeService/SendHeartbeat",
  "/msg.NodeService/ActionCommand",
  "/msg.NodeService/SendClientTransaction",
  "/msg.NodeService/SendTransCompleted",
};

std::unique_ptr< NodeService::Stub> NodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NodeService::Stub> stub(new NodeService::Stub(channel));
  return stub;
}

NodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendPrepare_(NodeService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendNewLogView_(NodeService_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SendAccept_(NodeService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendCommit_(NodeService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendHeartbeat_(NodeService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ActionCommand_(NodeService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientTransaction_(NodeService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendTransCompleted_(NodeService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NodeService::Stub::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare& request, ::msg::Acknowledge* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPrepare_, context, request, response);
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::AsyncSendPrepareRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrepare_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::PrepareAsyncSendPrepareRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrepare_, context, request, false);
}

::grpc::ClientReader< ::msg::Accepted>* NodeService::Stub::SendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::msg::Accepted>::Create(channel_.get(), rpcmethod_SendNewLogView_, context, request);
}

void NodeService::Stub::experimental_async::SendNewLogView(::grpc::ClientContext* context, ::msg::NewLogView* request, ::grpc::experimental::ClientReadReactor< ::msg::Accepted>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::msg::Accepted>::Create(stub_->channel_.get(), stub_->rpcmethod_SendNewLogView_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::msg::Accepted>* NodeService::Stub::AsyncSendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendNewLogView_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::msg::Accepted>* NodeService::Stub::PrepareAsyncSendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendNewLogView_, context, request, false, nullptr);
}

::grpc::Status NodeService::Stub::SendAccept(::grpc::ClientContext* context, const ::msg::Accept& request, ::msg::Accepted* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendAccept_, context, request, response);
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::msg::Accept* request, ::msg::Accepted* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Accepted* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::msg::Accept* request, ::msg::Accepted* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Accepted* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Accepted>* NodeService::Stub::AsyncSendAcceptRaw(::grpc::ClientContext* context, const ::msg::Accept& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendAccept_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Accepted>* NodeService::Stub::PrepareAsyncSendAcceptRaw(::grpc::ClientContext* context, const ::msg::Accept& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendAccept_, context, request, false);
}

::grpc::Status NodeService::Stub::SendCommit(::grpc::ClientContext* context, const ::msg::Commit& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendCommit_, context, request, response);
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::msg::Commit* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::msg::Commit* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendCommitRaw(::grpc::ClientContext* context, const ::msg::Commit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommit_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendCommitRaw(::grpc::ClientContext* context, const ::msg::Commit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommit_, context, request, false);
}

::grpc::Status NodeService::Stub::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendHeartbeat_, context, request, response);
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendHeartbeatRaw(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendHeartbeat_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendHeartbeatRaw(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendHeartbeat_, context, request, false);
}

::grpc::Status NodeService::Stub::ActionCommand(::grpc::ClientContext* context, const ::msg::Command& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ActionCommand_, context, request, response);
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::msg::Command* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::msg::Command* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncActionCommandRaw(::grpc::ClientContext* context, const ::msg::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_ActionCommand_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncActionCommandRaw(::grpc::ClientContext* context, const ::msg::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_ActionCommand_, context, request, false);
}

::grpc::Status NodeService::Stub::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::msg::TransAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendClientTransaction_, context, request, response);
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::AsyncSendClientTransactionRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientTransaction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::PrepareAsyncSendClientTransactionRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientTransaction_, context, request, false);
}

::grpc::Status NodeService::Stub::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendTransCompleted_, context, request, response);
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendTransCompletedRaw(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendTransCompleted_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendTransCompletedRaw(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendTransCompleted_, context, request, false);
}

NodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Prepare, ::msg::Acknowledge>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Prepare* req,
             ::msg::Acknowledge* resp) {
               return service->SendPrepare(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< NodeService::Service, ::msg::NewLogView, ::msg::Accepted>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::NewLogView* req,
             ::grpc_impl::ServerWriter<::msg::Accepted>* writer) {
               return service->SendNewLogView(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Accept, ::msg::Accepted>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Accept* req,
             ::msg::Accepted* resp) {
               return service->SendAccept(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Commit, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Commit* req,
             ::msg::Ack* resp) {
               return service->SendCommit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Heartbeat, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Heartbeat* req,
             ::msg::Ack* resp) {
               return service->SendHeartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Command, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Command* req,
             ::msg::Ack* resp) {
               return service->ActionCommand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::ClientTransaction, ::msg::TransAck>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::ClientTransaction* req,
             ::msg::TransAck* resp) {
               return service->SendClientTransaction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::TransCompleted, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::TransCompleted* req,
             ::msg::Ack* resp) {
               return service->SendTransCompleted(ctx, req, resp);
             }, this)));
}

NodeService::Service::~Service() {
}

::grpc::Status NodeService::Service::SendPrepare(::grpc::ServerContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendNewLogView(::grpc::ServerContext* context, const ::msg::NewLogView* request, ::grpc::ServerWriter< ::msg::Accepted>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendAccept(::grpc::ServerContext* context, const ::msg::Accept* request, ::msg::Accepted* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendCommit(::grpc::ServerContext* context, const ::msg::Commit* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendHeartbeat(::grpc::ServerContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::ActionCommand(::grpc::ServerContext* context, const ::msg::Command* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendClientTransaction(::grpc::ServerContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendTransCompleted(::grpc::ServerContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace msg

