// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto

#include "msg.pb.h"
#include "msg.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace msg {

static const char* NodeService_method_names[] = {
  "/msg.NodeService/SendPrePrepare",
  "/msg.NodeService/SendPrepare",
  "/msg.NodeService/SendPrepareLeader",
  "/msg.NodeService/SendPrepareFollower",
  "/msg.NodeService/SendCommitLeader",
  "/msg.NodeService/SendCommitFollower",
  "/msg.NodeService/SendViewChange",
  "/msg.NodeService/SendNewView",
  "/msg.NodeService/SendNewLogView",
  "/msg.NodeService/SendAccept",
  "/msg.NodeService/SendCommit",
  "/msg.NodeService/SendHeartbeat",
  "/msg.NodeService/ActionCommand",
  "/msg.NodeService/SendClientTransaction",
  "/msg.NodeService/SendClientReset",
  "/msg.NodeService/SendTransCompleted",
  "/msg.NodeService/SendClientRead",
};

std::unique_ptr< NodeService::Stub> NodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NodeService::Stub> stub(new NodeService::Stub(channel));
  return stub;
}

NodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendPrePrepare_(NodeService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendPrepare_(NodeService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendPrepareLeader_(NodeService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendPrepareFollower_(NodeService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendCommitLeader_(NodeService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendCommitFollower_(NodeService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendViewChange_(NodeService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendNewView_(NodeService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendNewLogView_(NodeService_method_names[8], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SendAccept_(NodeService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendCommit_(NodeService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendHeartbeat_(NodeService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ActionCommand_(NodeService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientTransaction_(NodeService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientReset_(NodeService_method_names[14], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendTransCompleted_(NodeService_method_names[15], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientRead_(NodeService_method_names[16], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NodeService::Stub::SendPrePrepare(::grpc::ClientContext* context, const ::msg::PrePrepare& request, ::msg::Acknowledge* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPrePrepare_, context, request, response);
}

void NodeService::Stub::experimental_async::SendPrePrepare(::grpc::ClientContext* context, const ::msg::PrePrepare* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrePrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrePrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrePrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrePrepare(::grpc::ClientContext* context, const ::msg::PrePrepare* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrePrepare_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendPrePrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrePrepare_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::AsyncSendPrePrepareRaw(::grpc::ClientContext* context, const ::msg::PrePrepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrePrepare_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::PrepareAsyncSendPrePrepareRaw(::grpc::ClientContext* context, const ::msg::PrePrepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrePrepare_, context, request, false);
}

::grpc::Status NodeService::Stub::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare& request, ::msg::Acknowledge* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPrepare_, context, request, response);
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendPrepare(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Acknowledge* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepare_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::AsyncSendPrepareRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrepare_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Acknowledge>* NodeService::Stub::PrepareAsyncSendPrepareRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Acknowledge>::Create(channel_.get(), cq, rpcmethod_SendPrepare_, context, request, false);
}

::grpc::Status NodeService::Stub::SendPrepareLeader(::grpc::ClientContext* context, const ::msg::Prepare& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPrepareLeader_, context, request, response);
}

void NodeService::Stub::experimental_async::SendPrepareLeader(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepareLeader_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepareLeader(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepareLeader_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepareLeader(::grpc::ClientContext* context, const ::msg::Prepare* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepareLeader_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendPrepareLeader(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepareLeader_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendPrepareLeaderRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendPrepareLeader_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendPrepareLeaderRaw(::grpc::ClientContext* context, const ::msg::Prepare& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendPrepareLeader_, context, request, false);
}

::grpc::Status NodeService::Stub::SendPrepareFollower(::grpc::ClientContext* context, const ::msg::PrepareCertificate& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPrepareFollower_, context, request, response);
}

void NodeService::Stub::experimental_async::SendPrepareFollower(::grpc::ClientContext* context, const ::msg::PrepareCertificate* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepareFollower_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepareFollower(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPrepareFollower_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendPrepareFollower(::grpc::ClientContext* context, const ::msg::PrepareCertificate* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepareFollower_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendPrepareFollower(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPrepareFollower_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendPrepareFollowerRaw(::grpc::ClientContext* context, const ::msg::PrepareCertificate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendPrepareFollower_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendPrepareFollowerRaw(::grpc::ClientContext* context, const ::msg::PrepareCertificate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendPrepareFollower_, context, request, false);
}

::grpc::Status NodeService::Stub::SendCommitLeader(::grpc::ClientContext* context, const ::msg::CommitLeader& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendCommitLeader_, context, request, response);
}

void NodeService::Stub::experimental_async::SendCommitLeader(::grpc::ClientContext* context, const ::msg::CommitLeader* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommitLeader_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommitLeader(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommitLeader_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommitLeader(::grpc::ClientContext* context, const ::msg::CommitLeader* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommitLeader_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendCommitLeader(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommitLeader_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendCommitLeaderRaw(::grpc::ClientContext* context, const ::msg::CommitLeader& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommitLeader_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendCommitLeaderRaw(::grpc::ClientContext* context, const ::msg::CommitLeader& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommitLeader_, context, request, false);
}

::grpc::Status NodeService::Stub::SendCommitFollower(::grpc::ClientContext* context, const ::msg::CommitCertificate& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendCommitFollower_, context, request, response);
}

void NodeService::Stub::experimental_async::SendCommitFollower(::grpc::ClientContext* context, const ::msg::CommitCertificate* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommitFollower_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommitFollower(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommitFollower_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommitFollower(::grpc::ClientContext* context, const ::msg::CommitCertificate* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommitFollower_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendCommitFollower(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommitFollower_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendCommitFollowerRaw(::grpc::ClientContext* context, const ::msg::CommitCertificate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommitFollower_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendCommitFollowerRaw(::grpc::ClientContext* context, const ::msg::CommitCertificate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommitFollower_, context, request, false);
}

::grpc::Status NodeService::Stub::SendViewChange(::grpc::ClientContext* context, const ::msg::ViewChange& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendViewChange_, context, request, response);
}

void NodeService::Stub::experimental_async::SendViewChange(::grpc::ClientContext* context, const ::msg::ViewChange* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendViewChange_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendViewChange(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendViewChange_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendViewChange(::grpc::ClientContext* context, const ::msg::ViewChange* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendViewChange_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendViewChange(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendViewChange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendViewChangeRaw(::grpc::ClientContext* context, const ::msg::ViewChange& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendViewChange_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendViewChangeRaw(::grpc::ClientContext* context, const ::msg::ViewChange& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendViewChange_, context, request, false);
}

::grpc::Status NodeService::Stub::SendNewView(::grpc::ClientContext* context, const ::msg::NewView& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendNewView_, context, request, response);
}

void NodeService::Stub::experimental_async::SendNewView(::grpc::ClientContext* context, const ::msg::NewView* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendNewView_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendNewView(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendNewView_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendNewView(::grpc::ClientContext* context, const ::msg::NewView* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendNewView_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendNewView(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendNewView_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendNewViewRaw(::grpc::ClientContext* context, const ::msg::NewView& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendNewView_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendNewViewRaw(::grpc::ClientContext* context, const ::msg::NewView& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendNewView_, context, request, false);
}

::grpc::ClientReader< ::msg::Accepted>* NodeService::Stub::SendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::msg::Accepted>::Create(channel_.get(), rpcmethod_SendNewLogView_, context, request);
}

void NodeService::Stub::experimental_async::SendNewLogView(::grpc::ClientContext* context, ::msg::NewLogView* request, ::grpc::experimental::ClientReadReactor< ::msg::Accepted>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::msg::Accepted>::Create(stub_->channel_.get(), stub_->rpcmethod_SendNewLogView_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::msg::Accepted>* NodeService::Stub::AsyncSendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendNewLogView_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::msg::Accepted>* NodeService::Stub::PrepareAsyncSendNewLogViewRaw(::grpc::ClientContext* context, const ::msg::NewLogView& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendNewLogView_, context, request, false, nullptr);
}

::grpc::Status NodeService::Stub::SendAccept(::grpc::ClientContext* context, const ::msg::Accept& request, ::msg::Accepted* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendAccept_, context, request, response);
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::msg::Accept* request, ::msg::Accepted* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Accepted* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::msg::Accept* request, ::msg::Accepted* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendAccept(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Accepted* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendAccept_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Accepted>* NodeService::Stub::AsyncSendAcceptRaw(::grpc::ClientContext* context, const ::msg::Accept& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendAccept_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Accepted>* NodeService::Stub::PrepareAsyncSendAcceptRaw(::grpc::ClientContext* context, const ::msg::Accept& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Accepted>::Create(channel_.get(), cq, rpcmethod_SendAccept_, context, request, false);
}

::grpc::Status NodeService::Stub::SendCommit(::grpc::ClientContext* context, const ::msg::Commit& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendCommit_, context, request, response);
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::msg::Commit* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::msg::Commit* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendCommit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendCommitRaw(::grpc::ClientContext* context, const ::msg::Commit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommit_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendCommitRaw(::grpc::ClientContext* context, const ::msg::Commit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendCommit_, context, request, false);
}

::grpc::Status NodeService::Stub::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendHeartbeat_, context, request, response);
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendHeartbeat(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendHeartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendHeartbeatRaw(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendHeartbeat_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendHeartbeatRaw(::grpc::ClientContext* context, const ::msg::Heartbeat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendHeartbeat_, context, request, false);
}

::grpc::Status NodeService::Stub::ActionCommand(::grpc::ClientContext* context, const ::msg::Command& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ActionCommand_, context, request, response);
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::msg::Command* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::msg::Command* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::ActionCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ActionCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncActionCommandRaw(::grpc::ClientContext* context, const ::msg::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_ActionCommand_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncActionCommandRaw(::grpc::ClientContext* context, const ::msg::Command& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_ActionCommand_, context, request, false);
}

::grpc::Status NodeService::Stub::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::msg::TransAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendClientTransaction_, context, request, response);
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendClientTransaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::AsyncSendClientTransactionRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientTransaction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::PrepareAsyncSendClientTransactionRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientTransaction_, context, request, false);
}

::grpc::Status NodeService::Stub::SendClientReset(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::msg::TransAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendClientReset_, context, request, response);
}

void NodeService::Stub::experimental_async::SendClientReset(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientReset_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientReset(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientReset_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientReset(::grpc::ClientContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientReset_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendClientReset(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::TransAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientReset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::AsyncSendClientResetRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientReset_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::TransAck>* NodeService::Stub::PrepareAsyncSendClientResetRaw(::grpc::ClientContext* context, const ::msg::ClientTransaction& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::TransAck>::Create(channel_.get(), cq, rpcmethod_SendClientReset_, context, request, false);
}

::grpc::Status NodeService::Stub::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::msg::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendTransCompleted_, context, request, response);
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendTransCompleted(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::Ack* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendTransCompleted_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::AsyncSendTransCompletedRaw(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendTransCompleted_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::Ack>* NodeService::Stub::PrepareAsyncSendTransCompletedRaw(::grpc::ClientContext* context, const ::msg::TransCompleted& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::Ack>::Create(channel_.get(), cq, rpcmethod_SendTransCompleted_, context, request, false);
}

::grpc::Status NodeService::Stub::SendClientRead(::grpc::ClientContext* context, const ::msg::ClientReadRequest& request, ::msg::ClientReadReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendClientRead_, context, request, response);
}

void NodeService::Stub::experimental_async::SendClientRead(::grpc::ClientContext* context, const ::msg::ClientReadRequest* request, ::msg::ClientReadReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientRead_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientRead(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::ClientReadReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendClientRead_, context, request, response, std::move(f));
}

void NodeService::Stub::experimental_async::SendClientRead(::grpc::ClientContext* context, const ::msg::ClientReadRequest* request, ::msg::ClientReadReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientRead_, context, request, response, reactor);
}

void NodeService::Stub::experimental_async::SendClientRead(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::msg::ClientReadReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendClientRead_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::ClientReadReply>* NodeService::Stub::AsyncSendClientReadRaw(::grpc::ClientContext* context, const ::msg::ClientReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::ClientReadReply>::Create(channel_.get(), cq, rpcmethod_SendClientRead_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::msg::ClientReadReply>* NodeService::Stub::PrepareAsyncSendClientReadRaw(::grpc::ClientContext* context, const ::msg::ClientReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::msg::ClientReadReply>::Create(channel_.get(), cq, rpcmethod_SendClientRead_, context, request, false);
}

NodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::PrePrepare, ::msg::Acknowledge>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::PrePrepare* req,
             ::msg::Acknowledge* resp) {
               return service->SendPrePrepare(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Prepare, ::msg::Acknowledge>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Prepare* req,
             ::msg::Acknowledge* resp) {
               return service->SendPrepare(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Prepare, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Prepare* req,
             ::msg::Ack* resp) {
               return service->SendPrepareLeader(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::PrepareCertificate, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::PrepareCertificate* req,
             ::msg::Ack* resp) {
               return service->SendPrepareFollower(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::CommitLeader, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::CommitLeader* req,
             ::msg::Ack* resp) {
               return service->SendCommitLeader(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::CommitCertificate, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::CommitCertificate* req,
             ::msg::Ack* resp) {
               return service->SendCommitFollower(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::ViewChange, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::ViewChange* req,
             ::msg::Ack* resp) {
               return service->SendViewChange(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::NewView, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::NewView* req,
             ::msg::Ack* resp) {
               return service->SendNewView(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< NodeService::Service, ::msg::NewLogView, ::msg::Accepted>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::NewLogView* req,
             ::grpc_impl::ServerWriter<::msg::Accepted>* writer) {
               return service->SendNewLogView(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Accept, ::msg::Accepted>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Accept* req,
             ::msg::Accepted* resp) {
               return service->SendAccept(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Commit, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Commit* req,
             ::msg::Ack* resp) {
               return service->SendCommit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Heartbeat, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Heartbeat* req,
             ::msg::Ack* resp) {
               return service->SendHeartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::Command, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::Command* req,
             ::msg::Ack* resp) {
               return service->ActionCommand(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::ClientTransaction, ::msg::TransAck>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::ClientTransaction* req,
             ::msg::TransAck* resp) {
               return service->SendClientTransaction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::ClientTransaction, ::msg::TransAck>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::ClientTransaction* req,
             ::msg::TransAck* resp) {
               return service->SendClientReset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::TransCompleted, ::msg::Ack>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::TransCompleted* req,
             ::msg::Ack* resp) {
               return service->SendTransCompleted(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::msg::ClientReadRequest, ::msg::ClientReadReply>(
          [](NodeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::msg::ClientReadRequest* req,
             ::msg::ClientReadReply* resp) {
               return service->SendClientRead(ctx, req, resp);
             }, this)));
}

NodeService::Service::~Service() {
}

::grpc::Status NodeService::Service::SendPrePrepare(::grpc::ServerContext* context, const ::msg::PrePrepare* request, ::msg::Acknowledge* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendPrepare(::grpc::ServerContext* context, const ::msg::Prepare* request, ::msg::Acknowledge* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendPrepareLeader(::grpc::ServerContext* context, const ::msg::Prepare* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendPrepareFollower(::grpc::ServerContext* context, const ::msg::PrepareCertificate* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendCommitLeader(::grpc::ServerContext* context, const ::msg::CommitLeader* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendCommitFollower(::grpc::ServerContext* context, const ::msg::CommitCertificate* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendViewChange(::grpc::ServerContext* context, const ::msg::ViewChange* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendNewView(::grpc::ServerContext* context, const ::msg::NewView* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendNewLogView(::grpc::ServerContext* context, const ::msg::NewLogView* request, ::grpc::ServerWriter< ::msg::Accepted>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendAccept(::grpc::ServerContext* context, const ::msg::Accept* request, ::msg::Accepted* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendCommit(::grpc::ServerContext* context, const ::msg::Commit* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendHeartbeat(::grpc::ServerContext* context, const ::msg::Heartbeat* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::ActionCommand(::grpc::ServerContext* context, const ::msg::Command* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendClientTransaction(::grpc::ServerContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendClientReset(::grpc::ServerContext* context, const ::msg::ClientTransaction* request, ::msg::TransAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendTransCompleted(::grpc::ServerContext* context, const ::msg::TransCompleted* request, ::msg::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::SendClientRead(::grpc::ServerContext* context, const ::msg::ClientReadRequest* request, ::msg::ClientReadReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace msg

